package:
    name: plutokore
    version: '0.8'

source:
    git_url: https://github.com/pmyates/plutokore.git
    git_rev: 0.8

build:
    noarch_python: True

requirements:
    build:
        - python
        - setuptools
        - numpy
        - astropy
        - matplotlib
        - tabulate
        - contextlib2
        - h5py
        - pyyaml
        - scipy
        - pytest
        - pytest-runner
        - pytest-datafiles
    run:
        - python
        - numpy
        - astropy
        - matplotlib
        - tabulate
        - contextlib2
        - h5py
        - pyyaml
        - scipy
        - pytest
        - pytest-runner
        - pytest-datafiles

test:
    imports:
        - plutokore

about:
    home: https://github.com/pmyates/plutokore
    license: GPL-3.0
    license_file: LICENSE
