package:
    name: plutokore
    version: '0.3'

source:
    git_url: https://github.com/opcon/plutokore.git
    git_rev: 0.3

build:
    noarch_python: True

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - astropy
        - matplotlib
        - tabulate
        - contextlib2

test:
    imports:
        - plutokore

about:
    home: https://github.com/opcon/plutokore
    license: MIT
    license_file: LICENSE
